\
\ Copyright (c) 2021 girlbrush all rights reserved.
\
\ @author: Tang Lai Lin, Tang Poh Ling, Faaliha Fazular Rahman
\ @date: 26 Nov 2023
\
\ The chatbot's initial display and main menu
\

: intro ( -- s )
    \ ctx{ ... } used to insert content into quotes ( q{ ... }q )
    
    \ "https://i.imgur.com/2wTTAD1.png" img ctx{ img }
    \ Replace the text below with the text above if you want to use a square image
    "https://i.imgur.com/2v1mJQT.jpg" circle-img ctx{ img }
    
    \ use of link buttons that have been styled in the ui.m file
    \ "Sundance Freestyle" "https://richbrian.lnk.to/SundanceFreestyle" link-btn ctx{ album }

    \ use buttons that have been styled in the ui.m file
    "Information Kiosks" btn-secondary ctx{ btn1 }
    "What are you looking for?" btn-secondary ctx{ btn2 }
    "Itinerary GPT" btn-secondary ctx{ btn3 }
    \ "FriendGPT" btn-secondary ctx{ btn5 }


    \ enter the ctx content using #{...} (without spaces)
    q{
        #{img}
        <h1 style="font-size: 1rem; text-align: center">
            😄 😄 😄
            <br>Welcome to our trend-spotting travel chatbot🧭! Stay updated on the 
            latest 🤩 and greatest places to explore in Singapore 🇸🇬.
        </h1>
        <br>
        <small style="opacity: .8">
            Explore trendy, delicious 🍗, fun 🎢, cultural 🎭, and adventurous 
            🏖️ places in Singapore. Enjoy thrilling or relaxing activities for
            all ages 👩🏼‍👨🏼‍👦🏼‍👧🏼. Travel easily with public transit 🚇.
        </small>
        #{btn1}
        #{btn2}
        #{btn3}
        <small style="opacity: .8">
            All right reserved to Merlion Jalan-Jalan
        </small>
    }q center
;

\ : reset-system-prompt ( -- ) 
\     "" system-content!
\ ;

Q: Itinerary GPT
\ B: reset-system-prompt
MM <center>
MM ${ embed-merlionGif }
MM Need help with your itinerary? Let me help you generate one according to your preferences! 
MM <br>
MM Remember, this response is generated by OpenAI. It may not accurately reflect real people, places, or facts.
MM </center>
MM ${ "ItineraryGPT" btn } 
\ MM ${ "FriendGPT" btn-secondary }
M. ${"Main Menu" btn-secondary}
K: $clear
--


Q: back
Q: main menu
A: ${ intro }
K: $clear
--







